set include BOOL off .

mod PCF-SYNTAX is
  sorts Var Type Exp .
  sorts Nat Bool .
  subsort Nat < Type .
  subsort Bool < Type .

  op 0 : -> Exp .
  op succ_ : Exp -> Exp .
  op pred_ : Exp -> Exp .
  op true : -> Exp .
  op false : -> Exp .
  op zero?_ : Exp -> Exp .
  op cond___ : Bool Exp Exp -> Exp .
  ops a b c d e f g h i j k l m n o p q r s t u v w x y z : -> Var . 
  op __ : Exp Exp -> Exp .
  op /\ _:_._ : Var Type Exp -> Exp .
  op u _:_._ : Var Type Exp -> Exp .
endm
